### ISSUE TITLE
Suggestion - Make it easier to dev w dockerized dataservice

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-study-creator#102]
I wanted to use my KF dataservice docker container with the KF study creator API container so that I could preload studies from my dataservice.

Not sure if this is the best approach, but I added the `kf-data-stack` user-defined network to both of the docker compose files for the dataservice and the study creator. Then I just set PRELOAD_DATA to `http://<dataservice web server container name>`

Maybe also add something to the sphinx docs about using your dockerized dataservice

**Comment by dankolbman** [comment]
This is a good point. We should be putting all of our service `docker-compose` files on the `kf-data-stack` network so that all containers will be connected, if the network is running.
The actual loading of the data will then be as you've outlined.
