### ISSUE TITLE
pass developer tokens by request header or message body, not as a URL query argument

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-api-study-creator#142]
Right now tokens are sent via `?token=` query argument, but that's not secure and not recommended.

https://tools.ietf.org/html/rfc6750#section-5.3 says:

> Don't pass bearer tokens in page URLs:  Bearer tokens SHOULD NOT be
      passed in page URLs (for example, as query string parameters).
      Instead, bearer tokens SHOULD be passed in HTTP message headers or
      message bodies for which confidentiality measures are taken.
      Browsers, web servers, and other software may not adequately
      secure URLs in the browser history, web server logs, and other
      data structures.  If bearer tokens are passed in page URLs,
      attackers might be able to steal them from the history data, logs,
      or other unsecured locations.

**Comment by dankolbman** [comment]
We also accept the token using the `Authorization` header. We could disable the use of developer tokens via url params, but we need to keep it for the signed urls, as there are no other options to authenticate browser requests.

**Comment by fiendish** [comment]
> We also accept the token using the Authorization header. 
@znatty22 ^

**Comment by znatty22** [comment]
Sounds good, the library already supports getting the token from the header or the URL query parameters.  It should be as easy as changing this setting in app settings: https://github.com/kids-first/kf-lib-data-ingest/blob/cb9e3a6d3fd3dcde0cae9e65575441997bed9b45/kf_lib_data_ingest/app/settings/development.py#L11

**Comment by fiendish** [comment]
@dankolbman Does using the Authorization actually work? I'm trying and getting 'Not authenticated to download the file.'

**Comment by dankolbman** [comment]
It looks like I was wrong and we don't try to parse the dev tokens out of the header.
I think I will address this by checking for a token prefixed with `Token ` under the authorization header and then attempting to resolve that.

**Comment by fiendish** [comment]
Why Token and not Bearer?

**Comment by znatty22** [comment]
Bearer seems to be part of the OAuth2 standard, but not necessarily a standard for all Token based auth

**Comment by fiendish** [comment]
I'm not so sure.
 http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml

**Comment by dankolbman** [comment]
`Bearer` implies it's using the OAuth2 scheme, which we do already use for auth so we should specify it as something else. `Token` is a common prefix, but it could be anything that isn't already formalized like `Basic`.

**Comment by fiendish** [comment]
> Bearer implies it's using the OAuth2 scheme

That's not true. From RFC 6750:

> While designed for use with access tokens
   resulting from OAuth 2.0 authorization [RFC6749] flows to access
   OAuth protected resources, this specification actually defines a
   general HTTP authorization method that can be used with bearer tokens
   from any source to access any resources protected by those bearer
   tokens.

**Comment by dankolbman** [comment]
ok, but it is implied within the context of this codebase.

**Comment by znatty22** [comment]
@fiendish I think study creator needs a way to differentiate JWT Bearer tokens which it receives in an OAuth2 based request and dev tokens which are different - see https://github.com/kids-first/kf-api-study-creator/blob/c1bed7283c2c6e323ed7f7d1e5422d0fd157aa8c/creator/files/models.py#L119. Using the `Token` keyword instead of `Bearer` in front of the token string is one way to differentiate and then parse the token string accordingly
