### ISSUE TITLE
downloaded files are given extra .html file extension

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-api-study-creator#144]
Clicking the download links on the files at https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_7NQ9151J/files downloads files that end in .html. If you strip the .html suffix, then the file contents appear to be correct.

**Comment by dankolbman** [comment]
It looks like we may have to wrap the `filename` in '"' or encode it differently.
Interesting discussion on it [here](https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http/216777).

**Comment by fiendish** [comment]
No. The problem is definitely this:
> content-type: text/html; charset=utf-8

**Comment by fiendish** [comment]
Per your original link, try setting `Content-Type: application/octet-stream`
