### ISSUE TITLE
Change filename header at download

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-study-creator#161]
The `filename` value in the response header when downloading a file should changed to:
1) Be sanitized of whitespace, replace spaces with '_'
2) Concatenate the version kf_id to the file
3) Add the version's extension automatically

This means users will get downloads with file names such as:
`MANIFEST_FV_00000000.csv`
`First_Batch.txt`

**Comment by fiendish** [comment]
I disagree with 1.
2 should be something more meaningful to regular users than a kfid, such as the upload time.
I don't know what 3 means.

**Comment by dankolbman** [comment]
Closed in favor of #178
