### ISSUE TITLE
Store and return version downloads with original file name

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-study-creator#178]
Files downloaded from the study creator should be named as they were uploaded.
To do this, we should add a `file_name` field to the `Version` model and use this name in the `attachment; filename=` header when offering it for download.

**Comment by bdolly** [comment]
I disagree with this as I feel it will lead to confusion around what a version is/means and may lead to people re-uploading a file version as a new file with a different name. I was thinking that maybe we could not call them `files` but rather `resources` so that you upload _data_ to a `resource`

**Comment by dankolbman** [comment]
@fiendish did say appending some version info to the original name would be fine, too. So perhaps we go with `{version.kf_id}_{version.file_name}`? I'm prefixing it here to avoid dealing with formats with multiple extensions, eg: `tar.gz`.

**Comment by fiendish** [comment]
yes, though I still think that KFIDs aren't ideal because a regular person can't look at two KFIDs and know which one is newer

**Comment by dankolbman** [comment]
We could also do time of upload, either timestamp alone or date combined with the kf id.
