### ISSUE TITLE
Extract feature settings

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-study-creator#504]
Our feature flags (`FEAT_`) and general settings currently need to be repeated across all our settings files although they are similar in all environments. We should be able to generalize these within one `features.py` file to reduce these repetitions when adding or changing features.

**Comment by znatty22** [comment]
Should we also DRY up the settings modules? All base settings in `development.py` or a `base.py` and then import that module in the `testing.py` and `production.py`

**Comment by dankolbman** [comment]
Right, that's what this will aim to achieve.
