### ISSUE TITLE
Change file primary key to uuid

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-study-creator#59]
The the primary key, `id`, on the `File` model is currently an incremental integer.
This should be changed to a unique uuid type to cause less confusion when evaluating a url.
The `id` field should also be renamed to `uuid` so that it will not conflict with the graphql `id` field.

**Comment by allisonheath** [comment]
Instead of UUID - do we want to consider the proposed change for KF IDs so we can be uniform across systems? https://github.com/kids-first/kf-api-dataservice/pull/454

**Comment by dankolbman** [comment]
We can do both
