### ISSUE TITLE
Data Service study generator for testing

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-study-creator#604]
We need to implement a study generator that produces fake realistic studies in the Data Service. 

It is very difficult to develop and test #502 with real studies in the Data Service since those studies are fairly large. Additionally, we need a more reliable way to test the ingest GWO task (and future ingest related functionality) without mocking out all of the responses from the Data Service.

**Comment by dankolbman** [comment]
We already have Dataservice as part of compose (`docker-compose.dataservice.yml`). What sort of tests do we want to run against it in Circle? This sounds like we'd be testing Dataservice, not so much study creator.

In terms of a study generator, I also have been adding some mock data during the creation of fake studies for my own local testing. See here for how I'm doing that: https://github.com/kids-first/kf-api-study-creator/blob/count-service/creator/studies/management/commands/fakestudies.py
