### ISSUE TITLE
Allow users to assign file type and report errors if req columns are missing

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-study-creator#633]
Right now when a user uploads a file they are only presented with the option to assign an expedited file type if their file contains all of the columns in the expedited file type. However, this isn't very informative since there is nothing to tell the user which columns their file is missing or how to modify their file so that it can be matched with one or more expedited types.

We should allow users to upload a file and select which expedited type they intend the file to be. Study creator should analyze the file and accept it as the selected expedited type if the file has all of the columns required by the expedited type. If the file is missing any required columns, then report which required columns are missing back to the user and do not allow them to complete the expedited file type assignment.

**Comment by dankolbman** [comment]
It seems this is perhaps more of a UI feature?

**Comment by znatty22** [comment]
@dankolbman Yea I wasn't sure if it could all be done on the frontend or if there would be backend work needed. If the file type definitions are hardcoded in the frontend src then maybe it could all be done in the frontend. I'll move this issue to kf-ui-data-tracker

**Comment by znatty22** [comment]
Moved to https://github.com/kids-first/kf-ui-data-tracker/issues/1029
