### ISSUE TITLE
Update pytest

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-study-creator#668]
It would be handy if we could update to the latest pytest. This may also help with conflicts that we have in the ingest library.

**Comment by gsantia** [comment]
`kf-lib-data-ingest 1.8.0 requires pytest==6.1.2, but you'll have pytest 6.2.4 which is incompatible.`

Would it be ok to go up to 6.1.2 instead?

**Comment by dankolbman** [comment]
Why does ingest library require that exact version? Maybe we should relax the version specified in ingest library.

**Comment by znatty22** [comment]
Not sure, would have to ask @fiendish. We probably don't need to be that strigent

**Comment by fiendish** [comment]
I'm very in favor of relaxing pins. that's just pip freeze being excessively strict.
