### ISSUE TITLE
Errors on DataTracker with Study related queries

### ISSUE THREAD

**Issue by gsantia** [kids-first/kf-api-study-creator#688]
When testing study creator with the master branch of the data tracker, `400` errors stemming from GraphQL posts pop up. It seems like they all deal with `Study`. The first example is when trying to create a new study (calling the `createStudy` mutation), the network tab says

>"Variable \"$input\" got invalid value {\"anticipatedSamples\": 0, \"attribution\": \"\", \"awardeeOrganization\": \"\", \"description\": \"\", \"externalId\": \"phs3300\", \"name\": \"d\", \"releaseDate\": null, \"shortName\": \"\", \"version\": \"\"}.\nIn field \"organization\": Expected \"ID!\", found null."

so it's expecting an organization ID and not receiving one (`phs3300` and `d` are the random data I entered).

Another example is when clicking on a study tab, the `getStudyReleases` query is called, and we get

>operationName: "GetStudyReleases"
query: "query GetStudyReleases($id: ID!) {\n  study(id: $id) {\n    id\n    releases(state: \"published\", orderBy: \"-created_at\") {\n      edges {\n        node {\n          id\n          kfId\n          name\n          description\n          state\n          creator {\n            ...UserFields\n            __typename\n          }\n          version\n          createdAt\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment UserFields on UserNode {\n  id\n  displayName\n  dateJoined\n  username\n  email\n  picture\n  __typename\n}\n"
variables: {}

so here the `variables` input is empty, but the query is expecting a study ID. I assume this has to do with the new organizations stuff pushed recently. Also, I wasn't entirely sure if I should put this under the data tracker repo or here.

EDIT: Seems like this is happening on production too.

**Comment by znatty22** [comment]
@gsantia This is when you're testing master branch of study creator with master branch of data tracker, correct?

**Comment by znatty22** [comment]
Also have you verified that the null value is being passed from the frontend to the backend? If the frontend is sending the correct GraphQL mutation/query then we know its a backend issue.

**Comment by gsantia** [comment]
> @gsantia This is when you're testing master branch of study creator with master branch of data tracker, correct?

yeah

**Comment by gsantia** [comment]
> Also have you verified that the null value is being passed from the frontend to the backend? If the frontend is sending the correct GraphQL mutation/query with correct input/variables then we know its a backend issue.

no, any tips on how to do that?

**Comment by gsantia** [comment]
For create study:

```
{operationName: "CREATE_STUDY", variables: {,…},…}
operationName: "CREATE_STUDY"
query: "mutation CREATE_STUDY($input: CreateStudyInput!, $workflows: [String]) {\n  createStudy(input: $input, workflows: $workflows) {\n    study {\n      ...StudyBasicFields\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment StudyBasicFields on StudyNode {\n  id\n  name\n  shortName\n  kfId\n  investigatorName\n  createdAt\n  modifiedAt\n  __typename\n}\n"
variables: {,…}
input: {externalId: "phs3300", name: "gio", shortName: "", description: "", releaseDate: null, version: "",…}
anticipatedSamples: 0
attribution: ""
awardeeOrganization: ""
description: ""
externalId: "phs3300"
name: "gio"
releaseDate: null
shortName: ""
version: ""
```

**Comment by gsantia** [comment]
`getStudyReleases` request payload on production:
```
{operationName: "GetStudyReleases", variables: {},…}
operationName: "GetStudyReleases"
query: "query GetStudyReleases($id: ID!) {\n  study(id: $id) {\n    id\n    releases(state: \"published\", orderBy: \"-created_at\") {\n      edges {\n        node {\n          id\n          kfId\n          name\n          description\n          state\n          creator {\n            ...UserFields\n            __typename\n          }\n          version\n          createdAt\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment UserFields on UserNode {\n  id\n  displayName\n  dateJoined\n  username\n  email\n  picture\n  __typename\n}\n"
variables: {}
```

**Comment by znatty22** [comment]
It's really hard to tell what's going on in those snippets. But I was going to suggest doing what you are, take a look at what is going into the request body and see if the frontend is populating things in input/variables with null. Then you know its a frontend issue

**Comment by dankolbman** [comment]
This is an issue with the frontend not invoking queries correctly. It seems like everything is working as expected on the API.
