### ISSUE TITLE
Download any templates as package endpoint

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-study-creator#727]
We need a new download endpoint for downloading any set of templates from the template admin view on Data Tracker. 

Currently templates can only be downloaded from the study's data template view. This works well for users that work within the context of a study but not for others (e.g. admins) that want to download templates from outside the study context (maybe they want to download another org's template and modify that to create a new one for their org).

**Task**
Implement new endpoint with similar functionality as the download study templates endpoint

```
/downloads/templates?file_format=[excel|zip]&template_versions=<comma separated list of TemplateVersion.id>
```

**Code**
Changes need to be made in these files

`creator/urls.py`
`creator/data_templates/views.py`

Please feel free to ask questions if anything is confusing or missing from this task description!

**Comment by gsantia** [comment]
Seems like changes will be need to be made to `creator/data_templates/packaging.py` as well, since the `study_template_package` function won't work here.
